### ISSUE TITLE
Drop `biome.requireConfiguration`?

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-biome#15]
It looks like the vscode extension dropped support for `biome.requireConfiguration`:

https://github.com/biomejs/biome-vscode/commit/c8daa722429f40ecea9fb8d1d19f1592b266de7b

Personally I kinda like it so not sure if we should follow...

**Comment by predrag-codetribe** [comment]
here is the reason why they dropped it https://github.com/biomejs/biome-vscode/issues/27#issue-2030645395

**Comment by predrag-codetribe** [comment]
It looks like it requires glue code on the client
It looks like plugin.py dont have such code
So I guess we can just remove the setting

**Comment by mstade** [comment]
Apologies for digging up an old issue, but I couldn't find the answer anywhere and it seems appropriate to ask here. Is it possible to define some fallback configuration in case there's no biome.json in the project, or just rely on Biome defaults?

I ask because I regularly have to edit files in a project where I'm unable to add such a configuration, but I'd stil like some sensible formatting defaults. As it stands, I can't seem to get Biome enabled at all unless that configuration file is available.
